version: "3.8"
services:
  # redis:
  #   image: redis:5.0.10
  #   container_name: fy_redis
  #   restart: always
  #   command: redis-server --requirepass Umph2014 --appendonly yes
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - /data/redis:/data
  # postgres:
  #   image: postgres:12.5
  #   container_name: fy_postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: postgres_prod
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: Umph2014
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - /data/postgresql:/var/lib/postgresql/data
  mysql:
    image: mysql:5.7.32
    container_name: fy_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Umph2014
      MYSQL_DATABASE: mysql_prod
      MYSQL_USER: glsroot
      MYSQL_PASSWORD: Umph2014
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
  mongo:
    image: mongo:4.4.2
    container_name: fy_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: glsroot
      MONGO_INITDB_ROOT_PASSWORD: Umph2014
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongod.conf.orig:/etc/mongod.conf.orig:ro
      - /data/mongo:/data/db
  nginx:
    image: nginx:1.19.5
    container_name: fy_nginx
    restart: always
    environment: 
      TZ: Asia/Shanghai
    ports: 
      - 80:80
      - 443:443
      - 8000:8000
    external_links: 
      - rails_demo:web_1
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx_html:/usr/share/nginx/html
      - ../heroku-ruby-boilerplate/public:/usr/share/nginx/html
      - ../fy_cert/4803322_fy1m.cn.pem:/etc/fy_cert/4803322_fy1m.cn.pem
      - ../fy_cert/4803322_fy1m.cn.key:/etc/fy_cert/4803322_fy1m.cn.key
    networks: 
      - heroku-ruby-boilerplate_app_net
networks: 
  heroku-ruby-boilerplate_app_net: 
    external: true