version: "3.7"
services: 
  nginx:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.dev
    container_name: fy-nginx
    restart: always
    image: nginx:1.19.5
    ports: 
      - 80:80
      - 443:443
      - 8000:8000
    environment: 
      - TZ=Asia/Shanghai
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_html:/usr/share/nginx/html
      - ./4803322_fy1m.cn.pem:/etc/fy1m_cert/4803322_fy1m.cn.pem
      - ./4803322_fy1m.cn.key:/etc/fy1m_cert/4803322_fy1m.cn.key
      # - fy-volumes:fy-data
#     networks: 
#       - fy-networks
#   redis:
#     image: redis:6.0.9-alpine
#     restart: always
#     ports:
#       - 6389:6379
#     networks: 
#       - fy-networks
#       networks: 
# fy-networks:
#   driver: bridge
#   external: true
# volumes: 
#   fy-volumes: