version: "3.1"
services: 
  nginx:
    restart: always
    image: nginx:1.19.5
    ports: 
      - 80:80
      - 443:443
      - 8000:8000
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_html:/usr/share/nginx/html
      - ./4803322_fy1m.cn.pem:/etc/fy1m_cert/4803322_fy1m.cn.pem
      - ./4803322_fy1m.cn.key:/etc/fy1m_cert/4803322_fy1m.cn.key
      # - fy-volumes:fy-data
    environment: 
      - TZ=Asia/Shanghai
#     networks: 
#       - fy-networks
# networks: 
#   fy-networks:
# volumes: 
#   fy-volumes:
