version: "3"
services: 
  nginx:
    image: nginx:1.19.5
    ports: 
      - "80:80"
    volumes: 
      - nginx.conf:/etc/nginx/conf.d/default.conf:ro
#       - fy-volumes:fy-data
#     networks: 
#       - fy-networks
# networks: 
#   fy-networks:
# volumes: 
#   fy-volumes:
