version: "3.8"

services:
  ruby_dev:
    container_name: ruby_container
    network_mode: host
    build:
      context: .
      network: host
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app