FROM node:12.20.0-alpine as node
# RUN yarn install --check-files
FROM ruby:2.6.5-alpine
COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /opt/yarn-* /opt/yarn
RUN ln -fs /opt/yarn/bin/yarn /usr/local/bin/yarn

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk update && apk add sqlite-dev build-base libxml2-dev libxslt-dev
RUN apk add postgresql-dev
RUN apk add busybox-extras

RUN apk add curl vim

WORKDIR /application
COPY . /application
RUN rm -rf yarn.lock
RUN echo "gem 'tzinfo-data'">>Gemfile
WORKDIR /application

RUN gem sources --remove https://rubygems.org/
RUN gem sources -a https://gems.ruby-china.com/
RUN gem sources -l
RUN gem install bundler:1.17.3
RUN bundle install --jobs=20
EXPOSE 3000
# CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
CMD ["rails", "server", "-b", "0.0.0.0"]
