version: '3.8'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      network: host
    network_mode: host
    container_name: rails_demo
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      # - redis
    # links:
    #   - postgres
    # command: bundle exec rails s -p 3000 -b "0.0.0.0"
    # command: ["rails", "server", "-b", "0.0.0.0"]
    environment:
      DATABASE_URL: postgres://postgres:Umph2014@postgres:5432/rails_server_development
  redis:
    image: redis:5.0.10
    container_name: fy_redis
    restart: always
    command: redis-server --requirepass Umph2014 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
  postgres:
    image: postgres:12.5
    container_name: fy_postgres
    restart: always
    environment:
      # POSTGRES_DB: postgres_prod
      POSTGRES_DB: rails_server_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Umph2014
    ports:
      - "5432:5432"
    volumes:
      - /data/postgresql:/var/lib/postgresql/data