version: '3.8'
services:
  web:
    # build: .
    network_mode: host
    build:
      context: .
      network: host
    ports:
      - "3000:3000"
    command: bundle exec rails server -u puma -b 0.0.0.0
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:12.5-alpine
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: todoapp